name: Run JPF

on:
  push:

jobs:
  run-jpf:
    name: '${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: e9725af236ea47991bfa27da110d680d0dd8f485
  
    - name: Set up JDK 17 for project
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: NPM Resolution (Linux)
      if: runner.os == 'Linux' 
      run: | 
        sudo apt-get update
        sudo apt-get install -y npm
        npm cache clean --force

    - name: NPM Resolution (macOS)
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install npm
        npm cache clean --force
    
    - name: Build project with JDK 17 (Linux)
      if: runner.os == 'Linux'
      run: |
          wget https://dlcdn.apache.org/maven/maven-3/3.9.7/binaries/apache-maven-3.9.7-bin.tar.gz
          tar xzf apache-maven-3.9.7-bin.tar.gz -C /opt
          sudo ln -s /opt/apache-maven-3.9.7/bin/mvn /usr/local/bin/mvn
          mvn clean install -DskipTests

    - name: Build project with JDK 17 (macOS)
      if: runner.os == 'macOS'
      run: |
        wget https://dlcdn.apache.org/maven/maven-3/3.9.7/binaries/apache-maven-3.9.7-bin.tar.gz
        sudo tar xzf apache-maven-3.9.7-bin.tar.gz -C /opt
        sudo ln -s /opt/apache-maven-3.9.7/bin/mvn /usr/local/bin/mvn
        mvn clean install -DskipTests
    
    - name: Set up JDK 11 for JPF
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Clone and build jpf-core
      run: |
        git clone https://github.com/javapathfinder/jpf-core.git /tmp/jpf-core
        cd /tmp/jpf-core
        ./gradlew buildJars

    - name: Run JPF on JAR files
      shell: bash
      run: |
        #!/bin/bash
        set +e 

        mkdir jpf_reports
        directory=$(pwd)
        runjpf_jar="/tmp/jpf-core/build/RunJPF.jar"
        jar_files=$(find "$directory" -type f -name "*.jar")
        
        for jar_file in $jar_files; do
            if ! unzip -l "$jar_file" 2>/dev/null | grep -q "META-INF/MANIFEST.MF"; then
                continue
            fi
            
            main_class=$(unzip -p "$jar_file" META-INF/MANIFEST.MF | grep -i 'Main-Class' | awk -F': ' '{print $2}' | tr -d '\r')
            
            if [ -z "$main_class" ]; then
                continue
            fi
            
            command="java -jar $runjpf_jar +classpath=$jar_file $main_class" 
            $command > "./jpf_reports/${main_class}_jpf_report.txt"
        done

    - name: Upload JPF reports
      uses: actions/upload-artifact@v4
      with:
        name: jpf-report-${{ github.event.repository.name}}-on-${{ matrix.os }}-from_branch_${{ github.ref_name }}
        path: './jpf_reports/*'
